# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import search_pb2 as search__pb2


class SearchStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SearchForString = channel.unary_unary(
        '/Search/SearchForString',
        request_serializer=search__pb2.SearchRequest.SerializeToString,
        response_deserializer=search__pb2.SearchResponse.FromString,
        )


class SearchServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SearchForString(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SearchServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SearchForString': grpc.unary_unary_rpc_method_handler(
          servicer.SearchForString,
          request_deserializer=search__pb2.SearchRequest.FromString,
          response_serializer=search__pb2.SearchResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Search', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class HealthCheckStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Check = channel.unary_unary(
        '/HealthCheck/Check',
        request_serializer=search__pb2.HealthCheckRequest.SerializeToString,
        response_deserializer=search__pb2.HealthCheckResponse.FromString,
        )


class HealthCheckServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Check(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HealthCheckServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Check': grpc.unary_unary_rpc_method_handler(
          servicer.Check,
          request_deserializer=search__pb2.HealthCheckRequest.FromString,
          response_serializer=search__pb2.HealthCheckResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'HealthCheck', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class FileTransferStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Transfer = channel.stream_unary(
        '/FileTransfer/Transfer',
        request_serializer=search__pb2.Chunk.SerializeToString,
        response_deserializer=search__pb2.UploadStatus.FromString,
        )


class FileTransferServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Transfer(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FileTransferServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Transfer': grpc.stream_unary_rpc_method_handler(
          servicer.Transfer,
          request_deserializer=search__pb2.Chunk.FromString,
          response_serializer=search__pb2.UploadStatus.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'FileTransfer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
